services:
    client:
      build: ./client
      container_name: client
      restart: always
      env_file:
         - ./client/.env
      ports:
         - "5173:5173" 


    server:
      build: ./server
      container_name: server
      restart: always
      env_file:
          - ./server/.env
      ports: 
          - "3000:3000"            