name : build-and-lint

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]  
jobs:
   build-and-lint:
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout repo
           uses: actions/checkout@v3

         - name: Setup Node
           uses: actions/setup-node@v3
           with:
             node-version: 22

         - name: Install backend dependencies
           working-directory: server
           run: npm ci

         - name: lint backend
           working-directory: server
           run: npm run lint -- --max-warnings=0

         - name: Install frontend dependencies
           working-directory: client
           run: npm ci

         - name: lint frontend 
           working-directory: client
           run: npm run lint -- --max-warnings=0

         - name: build backend image
           run:  docker build -t backend ./server

         - name: build frontend image
           run:  docker build -t frontend ./client    